name: CI/CD Pipeline for Genetic Disorder App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Allow JSON Content 🔥
        run: |
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> $GITHUB_ENV
          echo "WEBSITES_PORT=5000" >> $GITHUB_ENV
          echo "WEBSITES_ENABLE_APP_SERVICE_STORAGE=true" >> $GITHUB_ENV
          echo "WEBSITES_CONTAINER_START_TIME_LIMIT=1800" >> $GITHUB_ENV

      - name: Run Tests 🔬
        run: pytest || echo "No Tests Found"

      - name: Deploy to Azure 🚀
        uses: azure/webapps-deploy@v2
        with:
          app-name: "GeneticDisorderPrediction"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Purge Azure Cache 🔥
        run: |
          curl -X POST "https://${{ secrets.AZURE_WEBAPP_URL }}/?nocache=true"  